// src/pages/CompanyFunds.tsx
import { useState, useEffect } from 'react';
import { MainLayout } from '@/components/layout/MainLayout';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { 
  Wallet, 
  Save, 
  Loader2, 
  AlertCircle,
  TrendingUp,
  TrendingDown,
  History,
  DollarSign,
  Download,
  FileText,
  FileSpreadsheet
} from 'lucide-react';
import { exportToPDF, exportToXLSX } from '@/utils/exportUtils';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { format } from 'date-fns';
import { fr } from 'date-fns/locale';

interface CompanyFund {
  id: string;
  initial_capital: number;
  current_balance: number;
  notes: string | null;
  updated_by: string | null;
  created_at: string;
  updated_at: string;
}

interface FundHistory {
  id: string;
  previous_balance: number;
  new_balance: number;
  change_amount: number;
  change_type: string;
  notes: string | null;
  updated_by: string | null;
  created_at: string;
}

export default function CompanyFunds() {
  const { role, user } = useAuth();
  const [loading, setLoading] = useState(false);
  const [loadingData, setLoadingData] = useState(true);
  const [fund, setFund] = useState<CompanyFund | null>(null);
  const [history, setHistory] = useState<FundHistory[]>([]);
  const [initialCapital, setInitialCapital] = useState<string>('0');
  const [currentBalance, setCurrentBalance] = useState<string>('0');
  const [notes, setNotes] = useState('');
  const [showHistory, setShowHistory] = useState(false);

  // Vérifier l'accès
  const canManageFunds = role === 'admin' || role === 'directeur';

  useEffect(() => {
    if (!canManageFunds) return;
    loadFundData();
  }, [canManageFunds]);

  const loadFundData = async () => {
    setLoadingData(true);
    try {
      // Charger le fond actuel
      const { data: fundData, error: fundError } = await supabase
        .from('company_funds')
        .select('*')
        .order('created_at', { ascending: false })
        .limit(1)
        .maybeSingle();

      if (fundError) throw fundError;

      if (fundData) {
        setFund(fundData);
        setInitialCapital(fundData.initial_capital.toString());
        setCurrentBalance(fundData.current_balance.toString());
        setNotes(fundData.notes || '');
      } else {
        // Créer un fond initial si aucun n'existe
        const { data: newFund, error: createError } = await supabase
          .from('company_funds')
          .insert({
            initial_capital: 0,
            current_balance: 0,
            notes: 'Fond initial de l\'entreprise',
            updated_by: user?.id || null,
          })
          .select()
          .single();

        if (createError) throw createError;
        if (newFund) {
          setFund(newFund);
          setInitialCapital('0');
          setCurrentBalance('0');
          setNotes('Fond initial de l\'entreprise');
        }
      }

      // Charger l'historique
      if (fundData) {
        const { data: historyData, error: historyError } = await supabase
          .from('company_funds_history')
          .select('*')
          .eq('fund_id', fundData.id)
          .order('created_at', { ascending: false })
          .limit(50);

        if (historyError) throw historyError;
        setHistory(historyData || []);
      }
    } catch (error: any) {
      console.error('Error loading fund data:', error);
      toast.error('Erreur lors du chargement des données du fond');
    } finally {
      setLoadingData(false);
    }
  };

  const handleSave = async () => {
    if (!fund) return;

    setLoading(true);
    try {
      const initialCapitalNum = parseFloat(initialCapital.replace(/\s/g, '').replace(',', '.'));
      const currentBalanceNum = parseFloat(currentBalance.replace(/\s/g, '').replace(',', '.'));

      if (isNaN(initialCapitalNum) || initialCapitalNum < 0) {
        toast.error('Le capital initial doit être un nombre valide et positif');
        return;
      }

      if (isNaN(currentBalanceNum) || currentBalanceNum < 0) {
        toast.error('Le solde actuel doit être un nombre valide et positif');
        return;
      }

      const previousBalance = fund.current_balance;
      const changeAmount = currentBalanceNum - previousBalance;
      const changeType = previousBalance === 0 && currentBalanceNum > 0 ? 'initial_setup' : 'adjustment';

      // Mettre à jour le fond
      const { data: updatedFund, error: updateError } = await supabase
        .from('company_funds')
        .update({
          initial_capital: initialCapitalNum,
          current_balance: currentBalanceNum,
          notes: notes || null,
          updated_by: user?.id || null,
        })
        .eq('id', fund.id)
        .select()
        .single();

      if (updateError) throw updateError;

      // Enregistrer dans l'historique si le solde a changé
      if (changeAmount !== 0) {
        const { error: historyError } = await supabase
          .from('company_funds_history')
          .insert({
            fund_id: fund.id,
            previous_balance: previousBalance,
            new_balance: currentBalanceNum,
            change_amount: changeAmount,
            change_type: changeType,
            notes: notes || null,
            updated_by: user?.id || null,
          });

        if (historyError) {
          console.error('Error saving history:', historyError);
          // Ne pas bloquer la mise à jour si l'historique échoue
        }
      }

      setFund(updatedFund);
      toast.success('Fond de l\'entreprise mis à jour avec succès');
      loadFundData(); // Recharger pour avoir l'historique à jour
    } catch (error: any) {
      console.error('Error saving fund:', error);
      toast.error(error.message || 'Erreur lors de la sauvegarde du fond');
    } finally {
      setLoading(false);
    }
  };

  const formatCurrency = (amount: number) =>
    new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'XOF', maximumFractionDigits: 0 }).format(amount);

  const formatDate = (date: string) =>
    format(new Date(date), 'dd MMM yyyy à HH:mm', { locale: fr });

  const getChangeTypeLabel = (type: string) => {
    const labels: Record<string, string> = {
      initial_setup: 'Configuration initiale',
      adjustment: 'Ajustement',
      loan_disbursement: 'Décaissement de prêt',
      payment_received: 'Paiement reçu',
    };
    return labels[type] || type;
  };

  if (!canManageFunds) {
    return (
      <MainLayout>
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Accès refusé</AlertTitle>
          <AlertDescription>
            Seuls les administrateurs et les directeurs peuvent gérer le fond de l'entreprise.
          </AlertDescription>
        </Alert>
      </MainLayout>
    );
  }

  if (loadingData) {
    return (
      <MainLayout>
        <div className="flex items-center justify-center h-64">
          <Loader2 className="w-8 h-8 animate-spin text-primary" />
        </div>
      </MainLayout>
    );
  }

  return (
    <MainLayout>
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="font-display text-3xl font-bold flex items-center gap-3">
              <Wallet className="w-8 h-8" />
              Gestion du fond de l'entreprise
            </h1>
            <p className="text-muted-foreground mt-2">
              Définissez et gérez le capital initial et le solde actuel de l'entreprise
            </p>
          </div>
          <Button
            variant="outline"
            onClick={() => setShowHistory(!showHistory)}
            className="gap-2"
          >
            <History className="w-4 h-4" />
            {showHistory ? 'Masquer' : 'Afficher'} l'historique
          </Button>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Statistiques */}
          <Card className="lg:col-span-1">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <DollarSign className="w-5 h-5" />
                Solde actuel
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-bold text-primary">
                {fund ? formatCurrency(fund.current_balance) : formatCurrency(0)}
              </div>
              <p className="text-sm text-muted-foreground mt-2">
                Capital initial: {fund ? formatCurrency(fund.initial_capital) : formatCurrency(0)}
              </p>
            </CardContent>
          </Card>

          {/* Formulaire de gestion */}
          <Card className="lg:col-span-2">
            <CardHeader>
              <CardTitle>Paramètres du fond</CardTitle>
              <CardDescription>
                Modifiez le capital initial et le solde actuel de l'entreprise
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="initial-capital">Capital initial (XOF)</Label>
                <Input
                  id="initial-capital"
                  type="text"
                  value={initialCapital}
                  onChange={(e) => {
                    const value = e.target.value.replace(/[^\d,.-]/g, '');
                    setInitialCapital(value);
                  }}
                  placeholder="0"
                  className="text-lg"
                />
                <p className="text-sm text-muted-foreground">
                  Montant: {formatCurrency(parseFloat(initialCapital.replace(/\s/g, '').replace(',', '.')) || 0)}
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="current-balance">Solde actuel (XOF)</Label>
                <Input
                  id="current-balance"
                  type="text"
                  value={currentBalance}
                  onChange={(e) => {
                    const value = e.target.value.replace(/[^\d,.-]/g, '');
                    setCurrentBalance(value);
                  }}
                  placeholder="0"
                  className="text-lg"
                />
                <p className="text-sm text-muted-foreground">
                  Montant: {formatCurrency(parseFloat(currentBalance.replace(/\s/g, '').replace(',', '.')) || 0)}
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="notes">Notes (optionnel)</Label>
                <Textarea
                  id="notes"
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                  placeholder="Ajoutez des notes sur cette modification..."
                  rows={3}
                />
              </div>

              <Button
                onClick={handleSave}
                disabled={loading}
                className="w-full gap-2"
                size="lg"
              >
                {loading ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Enregistrement...
                  </>
                ) : (
                  <>
                    <Save className="w-4 h-4" />
                    Enregistrer les modifications
                  </>
                )}
              </Button>
            </CardContent>
          </Card>
        </div>

        {/* Historique */}
        {showHistory && (
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="flex items-center gap-2">
                    <History className="w-5 h-5" />
                    Historique des modifications
                  </CardTitle>
                  <CardDescription>
                    Liste des changements apportés au fond de l'entreprise
                  </CardDescription>
                </div>
                {history.length > 0 && (
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button variant="outline" size="sm">
                        <Download className="w-4 h-4 mr-2" />
                        Exporter
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                      <DropdownMenuItem onClick={() => {
                        const headers = ['Date', 'Type', 'Solde précédent', 'Nouveau solde', 'Variation', 'Notes'];
                        const rows = history.map(entry => [
                          formatDate(entry.created_at),
                          getChangeTypeLabel(entry.change_type),
                          formatCurrency(entry.previous_balance),
                          formatCurrency(entry.new_balance),
                          formatCurrency(entry.change_amount),
                          entry.notes || '-',
                        ]);
                        exportToPDF(rows, headers, `historique-fond-${format(new Date(), 'yyyy-MM-dd')}`, 'Historique du fond de l\'entreprise');
                      }}>
                        <FileText className="w-4 h-4 mr-2" />
                        Exporter en PDF
                      </DropdownMenuItem>
                      <DropdownMenuItem onClick={() => {
                        const headers = ['Date', 'Type', 'Solde précédent', 'Nouveau solde', 'Variation', 'Notes'];
                        const rows = history.map(entry => [
                          formatDate(entry.created_at),
                          getChangeTypeLabel(entry.change_type),
                          formatCurrency(entry.previous_balance),
                          formatCurrency(entry.new_balance),
                          formatCurrency(entry.change_amount),
                          entry.notes || '-',
                        ]);
                        exportToXLSX(rows, headers, `historique-fond-${format(new Date(), 'yyyy-MM-dd')}`, 'Historique');
                      }}>
                        <FileSpreadsheet className="w-4 h-4 mr-2" />
                        Exporter en Excel (XLSX)
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                )}
              </div>
            </CardHeader>
            <CardContent>
              {history.length > 0 ? (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Date</TableHead>
                      <TableHead>Type</TableHead>
                      <TableHead>Solde précédent</TableHead>
                      <TableHead>Nouveau solde</TableHead>
                      <TableHead>Variation</TableHead>
                      <TableHead>Notes</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {history.map((entry) => (
                      <TableRow key={entry.id}>
                        <TableCell className="text-muted-foreground">
                          {formatDate(entry.created_at)}
                        </TableCell>
                        <TableCell>
                          <span className="inline-flex items-center gap-1 px-2 py-1 rounded-md bg-muted text-sm">
                            {entry.change_type === 'initial_setup' && <TrendingUp className="w-3 h-3" />}
                            {entry.change_type === 'adjustment' && (
                              entry.change_amount > 0 ? (
                                <TrendingUp className="w-3 h-3 text-green-600" />
                              ) : (
                                <TrendingDown className="w-3 h-3 text-red-600" />
                              )
                            )}
                            {getChangeTypeLabel(entry.change_type)}
                          </span>
                        </TableCell>
                        <TableCell>{formatCurrency(entry.previous_balance)}</TableCell>
                        <TableCell className="font-medium">
                          {formatCurrency(entry.new_balance)}
                        </TableCell>
                        <TableCell
                          className={`font-medium ${
                            entry.change_amount > 0
                              ? 'text-green-600'
                              : entry.change_amount < 0
                              ? 'text-red-600'
                              : ''
                          }`}
                        >
                          {entry.change_amount > 0 ? '+' : ''}
                          {formatCurrency(entry.change_amount)}
                        </TableCell>
                        <TableCell className="text-muted-foreground text-sm">
                          {entry.notes || '-'}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              ) : (
                <div className="text-center py-8 text-muted-foreground">
                  <p>Aucun historique disponible</p>
                </div>
              )}
            </CardContent>
          </Card>
        )}
      </div>
    </MainLayout>
  );
}

// app/pages/company-funds/index.vue
<script setup lang="ts">
import NumberFlow from '@number-flow/vue'
import { History, Wallet } from 'lucide-vue-next'

definePageMeta({ layout: 'default' })

interface Fund {
  id: string
  initial_capital: number
  current_balance: number
  total_loans_disbursed: number | null
  total_interest_earned: number | null
  total_payments_received: number | null
  notes: string | null
  updated_by: string | null
  created_at: string
  updated_at: string
}

interface FundHistoryRow {
  id: string
  fund_id: string
  previous_balance: number
  new_balance: number
  change_amount: number
  change_type: string
  notes: string | null
  created_at: string
}

const changeTypeLabels: Record<string, string> = {
  initial_setup: 'Création / capital initial',
  adjustment: 'Ajustement',
  loan_disbursement: 'Déblocage prêt',
  payment_received: 'Paiement reçu',
  expense: 'Dépense',
}

const funds = ref<Fund[]>([])
const history = ref<FundHistoryRow[]>([])
const loading = ref(true)
const error = ref('')
const saving = ref(false)
const createForm = ref({ initial_capital: 0, notes: '' })
const adjustmentForm = ref({ amount: 0, notes: '' })
const updateForm = ref({ initial_capital: 0, notes: '' })

const { role } = useAuthRole()
const supabase = useSupabase().value
const canEdit = computed(() => role.value === 'directeur')

const mainFund = computed(() => funds.value[0] ?? null)

async function fetchFunds() {
  loading.value = true
  error.value = ''
  try {
    if (!supabase) {
      error.value = 'Supabase non configuré.'
      return
    }
    const { data, error: e } = await supabase.from('company_funds').select('*').order('created_at', { ascending: true })
    if (e)
      throw e
    funds.value = (data ?? []) as Fund[]
    if (funds.value.length > 0) {
      const fundId = funds.value[0].id
      const { data: histData, error: eH } = await supabase
        .from('company_funds_history')
        .select('id, fund_id, previous_balance, new_balance, change_amount, change_type, notes, created_at')
        .eq('fund_id', fundId)
        .order('created_at', { ascending: false })
        .limit(50)
      if (!eH)
        history.value = (histData ?? []) as FundHistoryRow[]
      else history.value = []
    }
    else {
      history.value = []
    }
  }
  catch (e: any) {
    error.value = e?.message || 'Erreur chargement fonds'
  }
  finally {
    loading.value = false
  }
}

async function createFund() {
  if (!canEdit.value || !supabase)
    return
  const cap = Number(createForm.value.initial_capital)
  if (Number.isNaN(cap) || cap < 0) {
    error.value = 'Le capital initial doit être un nombre positif.'
    return
  }
  saving.value = true
  error.value = ''
  try {
    const { data: { user } } = await supabase.auth.getUser()
    const { data: inserted, error: e } = await supabase
      .from('company_funds')
      .insert({
        initial_capital: cap,
        current_balance: cap,
        total_loans_disbursed: 0,
        total_interest_earned: 0,
        total_payments_received: 0,
        notes: createForm.value.notes?.trim() || null,
        updated_by: user?.id ?? null,
      })
      .select('id')
      .single()
    if (e)
      throw e
    const fundId = (inserted as { id: string }).id
    await supabase.from('company_funds_history').insert({
      fund_id: fundId,
      previous_balance: 0,
      new_balance: cap,
      change_amount: cap,
      change_type: 'initial_setup',
      notes: createForm.value.notes?.trim() || null,
      updated_by: user?.id ?? null,
    })
    createForm.value = { initial_capital: 0, notes: '' }
    await fetchFunds()
  }
  catch (e: any) {
    error.value = e?.message || 'Erreur création fonds'
  }
  finally {
    saving.value = false
  }
}

async function applyAdjustment() {
  const f = mainFund.value
  if (!canEdit.value || !supabase || !f)
    return
  const amount = Number(adjustmentForm.value.amount)
  if (Number.isNaN(amount) || amount === 0) {
    error.value = 'Indiquez un montant (positif pour ajouter, négatif pour retirer).'
    return
  }
  const newBalance = f.current_balance + amount
  if (newBalance < 0) {
    error.value = 'Le solde ne peut pas devenir négatif.'
    return
  }
  saving.value = true
  error.value = ''
  try {
    const { data: { user } } = await supabase.auth.getUser()
    const { error: e } = await supabase
      .from('company_funds')
      .update({
        current_balance: newBalance,
        notes: updateForm.value.notes?.trim() || f.notes,
        updated_by: user?.id ?? null,
      })
      .eq('id', f.id)
    if (e)
      throw e
    await supabase.from('company_funds_history').insert({
      fund_id: f.id,
      previous_balance: f.current_balance,
      new_balance: newBalance,
      change_amount: amount,
      change_type: 'adjustment',
      notes: adjustmentForm.value.notes?.trim() || null,
      updated_by: user?.id ?? null,
    })
    adjustmentForm.value = { amount: 0, notes: '' }
    await fetchFunds()
  }
  catch (e: any) {
    error.value = e?.message || 'Erreur ajustement'
  }
  finally {
    saving.value = false
  }
}

async function updateFundDetails() {
  const f = mainFund.value
  if (!canEdit.value || !supabase || !f)
    return
  const cap = Number(updateForm.value.initial_capital)
  if (Number.isNaN(cap) || cap < 0) {
    error.value = 'Le capital initial doit être un nombre positif.'
    return
  }
  saving.value = true
  error.value = ''
  try {
    const { data: { user } } = await supabase.auth.getUser()
    const { error: e } = await supabase
      .from('company_funds')
      .update({
        initial_capital: cap,
        notes: updateForm.value.notes?.trim() || null,
        updated_by: user?.id ?? null,
      })
      .eq('id', f.id)
    if (e)
      throw e
    await fetchFunds()
  }
  catch (e: any) {
    error.value = e?.message || 'Erreur mise à jour'
  }
  finally {
    saving.value = false
  }
}

function initUpdateForm() {
  const f = mainFund.value
  if (f) {
    updateForm.value = {
      initial_capital: f.initial_capital,
      notes: f.notes ?? '',
    }
  }
}

onMounted(() => fetchFunds())
watch(mainFund, (f) => {
  if (f)
    initUpdateForm()
}, { immediate: true })
</script>

<template>
  <div class="w-full flex flex-col gap-6">
    <h2 class="text-2xl font-bold tracking-tight">
      Fonds de trésorerie
    </h2>
    <p class="text-muted-foreground text-sm">
      Solde et indicateurs liés aux prêts (déblocages et paiements reçus). Le directeur peut créer le fonds, faire des ajustements et modifier les informations.
    </p>
    <p v-if="error" class="text-destructive text-sm">
      {{ error }}
    </p>

    <template v-if="loading">
      <p class="text-muted-foreground">
        Chargement…
      </p>
    </template>
    <template v-else>
      <!-- Aucun fonds : création (directeur uniquement) -->
      <Card v-if="funds.length === 0">
        <CardHeader>
          <CardTitle class="text-base">
            Créer le fonds de trésorerie
          </CardTitle>
          <CardDescription>
            Aucun fonds enregistré. Définissez le capital initial pour commencer.
          </CardDescription>
        </CardHeader>
        <CardContent v-if="canEdit">
          <form class="flex flex-col gap-4 max-w-sm" @submit.prevent="createFund">
            <div class="grid gap-2">
              <Label for="init_cap">Capital initial (XOF) *</Label>
              <Input id="init_cap" v-model.number="createForm.initial_capital" type="number" min="0" step="1" required />
            </div>
            <div class="grid gap-2">
              <Label for="init_notes">Notes</Label>
              <Input id="init_notes" v-model="createForm.notes" placeholder="Optionnel" />
            </div>
            <Button type="submit" :disabled="saving">
              {{ saving ? 'Création…' : 'Créer le fonds' }}
            </Button>
          </form>
        </CardContent>
        <p v-else class="text-muted-foreground text-sm">
          Seul le directeur peut créer le fonds. Contactez-le pour initialiser la trésorerie.
        </p>
      </Card>

      <template v-else>
        <!-- Vue d’ensemble -->
        <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          <Card v-for="f in funds" :key="f.id">
            <CardHeader class="flex flex-row items-center justify-between pb-2">
              <CardTitle class="text-sm font-medium">
                Trésorerie
              </CardTitle>
              <Wallet class="size-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <p class="text-2xl font-bold tabular-nums">
                <NumberFlow :value="f.current_balance" :format="{ style: 'currency', currency: 'XOF' }" />
              </p>
              <p class="text-muted-foreground text-xs mt-1">
                Capital initial : <NumberFlow :value="f.initial_capital" :format="{ style: 'currency', currency: 'XOF' }" />
              </p>
              <div class="mt-3 flex flex-col gap-1 text-sm text-muted-foreground">
                <span>Prêts débloqués : <NumberFlow :value="f.total_loans_disbursed ?? 0" :format="{ style: 'currency', currency: 'XOF' }" /></span>
                <span>Intérêts perçus : <NumberFlow :value="f.total_interest_earned ?? 0" :format="{ style: 'currency', currency: 'XOF' }" /></span>
                <span>Paiements reçus : <NumberFlow :value="f.total_payments_received ?? 0" :format="{ style: 'currency', currency: 'XOF' }" /></span>
              </div>
            </CardContent>
          </Card>
        </div>

        <!-- Modifier le fonds (directeur) -->
        <div v-if="canEdit && mainFund" class="grid gap-4 md:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle class="text-base">
                Ajustement du solde
              </CardTitle>
              <CardDescription>
                Ajouter (montant positif) ou retirer (montant négatif) de la trésorerie.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form class="flex flex-col gap-4" @submit.prevent="applyAdjustment">
                <div class="grid gap-2">
                  <Label for="adj_amount">Montant (XOF) — positif = entrée, négatif = sortie</Label>
                  <Input id="adj_amount" v-model.number="adjustmentForm.amount" type="number" step="1" placeholder="0" />
                </div>
                <div class="grid gap-2">
                  <Label for="adj_notes">Motif / notes</Label>
                  <Input id="adj_notes" v-model="adjustmentForm.notes" placeholder="Optionnel" />
                </div>
                <Button type="submit" :disabled="saving">
                  {{ saving ? 'Enregistrement…' : 'Appliquer l’ajustement' }}
                </Button>
              </form>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle class="text-base">
                Modifier les informations
              </CardTitle>
              <CardDescription>
                Capital initial (affiché) et notes. N’affecte pas le solde actuel.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form class="flex flex-col gap-4" @submit.prevent="updateFundDetails">
                <div class="grid gap-2">
                  <Label for="upd_cap">Capital initial (XOF)</Label>
                  <Input id="upd_cap" v-model.number="updateForm.initial_capital" type="number" min="0" step="1" />
                </div>
                <div class="grid gap-2">
                  <Label for="upd_notes">Notes</Label>
                  <Input id="upd_notes" v-model="updateForm.notes" placeholder="Optionnel" />
                </div>
                <Button type="submit" variant="outline" :disabled="saving">
                  {{ saving ? 'Enregistrement…' : 'Enregistrer' }}
                </Button>
              </form>
            </CardContent>
          </Card>
        </div>

        <!-- Historique -->
        <Card v-if="mainFund">
          <CardHeader>
            <CardTitle class="text-base flex items-center gap-2">
              <History class="size-4" />
              Historique des mouvements
            </CardTitle>
            <CardDescription>
              Derniers mouvements du fonds (déblocages prêts, paiements, ajustements).
            </CardDescription>
          </CardHeader>
          <CardContent class="p-0">
            <Table v-if="history.length > 0">
              <TableHeader>
                <TableRow>
                  <TableHead>Date</TableHead>
                  <TableHead>Type</TableHead>
                  <TableHead>Montant</TableHead>
                  <TableHead>Solde après</TableHead>
                  <TableHead>Notes</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow v-for="h in history" :key="h.id">
                  <TableCell class="text-muted-foreground text-sm">
                    {{ new Date(h.created_at).toLocaleString('fr-FR') }}
                  </TableCell>
                  <TableCell>{{ changeTypeLabels[h.change_type] ?? h.change_type }}</TableCell>
                  <TableCell class="tabular-nums">
                    <NumberFlow :value="h.change_amount" :format="{ style: 'currency', currency: 'XOF' }" />
                  </TableCell>
                  <TableCell class="tabular-nums">
                    <NumberFlow :value="h.new_balance" :format="{ style: 'currency', currency: 'XOF' }" />
                  </TableCell>
                  <TableCell class="text-muted-foreground text-sm">
                    {{ h.notes || '—' }}
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
            <div v-else class="py-8 text-center text-muted-foreground text-sm">
              Aucun mouvement enregistré.
            </div>
          </CardContent>
        </Card>
      </template>
    </template>
  </div>
</template>
