// app/pages/clients/index.vue
<script setup lang="ts">
import type { Database } from '~/types/database'
import { Mail, Phone, Plus, Search } from 'lucide-vue-next'

definePageMeta({ layout: 'default' })

type ClientRow = Database['public']['Tables']['clients']['Row']

const clients = ref<ClientRow[]>([])
const loading = ref(true)
const error = ref('')
const search = ref('')

async function fetchClients() {
  loading.value = true
  error.value = ''
  try {
    const supabase = useSupabase()
    if (!supabase) {
      error.value = 'Supabase non configuré.'
      return
    }
    const { data, error: e } = await supabase
      .from('clients')
      .select('*')
      .order('created_at', { ascending: false })
    if (e)
      throw e
    clients.value = data ?? []
  }
  catch (e: any) {
    error.value = e?.message || 'Erreur chargement clients'
  }
  finally {
    loading.value = false
  }
}

const filteredClients = computed(() => {
  const q = search.value.trim().toLowerCase()
  if (!q)
    return clients.value
  return clients.value.filter(c =>
    c.full_name.toLowerCase().includes(q)
    || (c.phone && c.phone.includes(q))
    || (c.email && c.email.toLowerCase().includes(q))
    || (c.id_number && c.id_number.toLowerCase().includes(q)),
  )
})

onMounted(() => fetchClients())
</script>

<template>
  <div class="w-full flex flex-col gap-4">
    <div class="flex flex-wrap items-center justify-between gap-2">
      <h2 class="text-2xl font-bold tracking-tight">
        Clients
      </h2>
      <div class="flex items-center gap-2">
        <div class="relative w-64">
          <Search class="absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            v-model="search"
            placeholder="Rechercher (nom, téléphone, email…)"
            class="pl-8"
          />
        </div>
        <Button as-child>
          <NuxtLink to="/clients/new">
            <Plus class="mr-2 size-4" />
            Nouveau client
          </NuxtLink>
        </Button>
      </div>
    </div>

    <p v-if="error" class="text-destructive text-sm">
      {{ error }}
    </p>

    <Card v-else>
      <CardContent class="p-0">
        <div v-if="loading" class="flex items-center justify-center py-12">
          <p class="text-muted-foreground">
            Chargement…
          </p>
        </div>
        <template v-else>
          <Table v-if="filteredClients.length > 0">
            <TableHeader>
              <TableRow>
                <TableHead>Nom</TableHead>
                <TableHead>Téléphone</TableHead>
                <TableHead>Email</TableHead>
                <TableHead>Pièce</TableHead>
                <TableHead>Créé le</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow v-for="c in filteredClients" :key="c.id">
                <TableCell class="font-medium">
                  <NuxtLink :to="`/clients/${c.id}`" class="hover:underline">
                    {{ c.full_name }}
                  </NuxtLink>
                </TableCell>
                <TableCell>
                  <span class="flex items-center gap-1.5">
                    <Phone class="size-3.5 text-muted-foreground" />
                    {{ c.phone }}
                  </span>
                </TableCell>
                <TableCell>
                  <span v-if="c.email" class="flex items-center gap-1.5">
                    <Mail class="size-3.5 text-muted-foreground" />
                    {{ c.email }}
                  </span>
                  <span v-else class="text-muted-foreground">—</span>
                </TableCell>
                <TableCell>
                  {{ c.id_type }} {{ c.id_number }}
                </TableCell>
                <TableCell class="text-muted-foreground text-sm">
                  {{ new Date(c.created_at).toLocaleDateString('fr-FR') }}
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
          <div v-else class="py-12 text-center text-muted-foreground">
            Aucun client trouvé.
          </div>
        </template>
      </CardContent>
    </Card>
  </div>
</template>

// src/pages/Clients.tsx
import { useEffect, useState } from 'react';
import { MainLayout } from '@/components/layout/MainLayout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';
import { Plus, Search, Phone, Mail } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { Link } from 'react-router-dom';

interface Client {
  id: string;
  full_name: string;
  email: string | null;
  phone: string;
  profession: string | null;
  created_at: string;
}

export default function Clients() {
  const [clients, setClients] = useState<Client[]>([]);
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchClients = async () => {
      const { data } = await supabase
        .from('clients')
        .select('*')
        .order('created_at', { ascending: false });
      setClients(data || []);
      setLoading(false);
    };
    fetchClients();
  }, []);

  const filteredClients = clients.filter(c =>
    c.full_name.toLowerCase().includes(search.toLowerCase()) ||
    c.phone.includes(search)
  );

  return (
    <MainLayout>
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <h1 className="font-display text-3xl font-bold">Clients</h1>
          <Link to="/clients/new">
            <Button className="gap-2">
              <Plus className="w-4 h-4" />
              Nouveau client
            </Button>
          </Link>
        </div>

        <div className="relative max-w-md">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <Input
            placeholder="Rechercher un client..."
            className="pl-10"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>

        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {[...Array(6)].map((_, i) => (
              <Card key={i} className="animate-pulse">
                <CardContent className="p-6">
                  <div className="h-6 bg-muted rounded w-2/3 mb-4" />
                  <div className="h-4 bg-muted rounded w-1/2" />
                </CardContent>
              </Card>
            ))}
          </div>
        ) : filteredClients.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {filteredClients.map((client) => (
              <Link key={client.id} to={`/clients/${client.id}`}>
                <Card className="hover:shadow-md transition-shadow cursor-pointer">
                  <CardContent className="p-6">
                    <div className="flex items-center gap-4">
                      <div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center">
                        <span className="text-lg font-semibold text-primary">
                          {client.full_name.charAt(0)}
                        </span>
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="font-medium text-foreground truncate">{client.full_name}</p>
                        <p className="text-sm text-muted-foreground">{client.profession || 'Non renseigné'}</p>
                      </div>
                    </div>
                    <div className="mt-4 space-y-2">
                      <div className="flex items-center gap-2 text-sm text-muted-foreground">
                        <Phone className="w-4 h-4" />
                        <span>{client.phone}</span>
                      </div>
                      {client.email && (
                        <div className="flex items-center gap-2 text-sm text-muted-foreground">
                          <Mail className="w-4 h-4" />
                          <span className="truncate">{client.email}</span>
                        </div>
                      )}
                    </div>
                  </CardContent>
                </Card>
              </Link>
            ))}
          </div>
        ) : (
          <div className="text-center py-12 text-muted-foreground">
            <p>Aucun client trouvé</p>
          </div>
        )}
      </div>
    </MainLayout>
  );
}
