// app/pages/loans/index.vue
<script setup lang="ts">
import type { LoanStatus } from '~/types/database'
import NumberFlow from '@number-flow/vue'
import { HandCoins } from 'lucide-vue-next'

definePageMeta({ layout: 'default' })

interface LoanWithClient {
  id: string
  client_id: string
  amount: number
  interest_rate: number
  duration_months: number
  status: LoanStatus
  total_amount: number | null
  monthly_payment: number | null
  purpose: string | null
  disbursement_date: string | null
  created_at: string
  clients?: { full_name: string } | null
}

const loans = ref<LoanWithClient[]>([])
const loading = ref(true)
const error = ref('')

const statusLabels: Record<LoanStatus, string> = {
  en_attente: 'En attente',
  valide: 'Validé',
  en_cours: 'En cours',
  rembourse: 'Remboursé',
  en_retard: 'En retard',
  defaut: 'Défaut',
}

async function fetchLoans() {
  loading.value = true
  error.value = ''
  try {
    const supabase = useSupabase()
    if (!supabase) {
      error.value = 'Supabase non configuré.'
      return
    }
    const { data, error: e } = await supabase
      .from('loans')
      .select('id, client_id, amount, interest_rate, duration_months, status, total_amount, monthly_payment, purpose, disbursement_date, created_at, clients(full_name)')
      .order('created_at', { ascending: false })
    if (e) throw e
    loans.value = (data ?? []).map((row: any) => ({
      ...row,
      clients: Array.isArray(row.clients) ? row.clients[0] : row.clients,
    }))
  }
  catch (e: any) {
    error.value = e?.message || 'Erreur chargement prêts'
  }
  finally {
    loading.value = false
  }
}

function clientName(loan: LoanWithClient) {
  const c = loan.clients
  return (c && typeof c === 'object' && 'full_name' in c) ? (c as { full_name: string }).full_name : '—'
}

onMounted(() => fetchLoans())
</script>

<template>
  <div class="w-full flex flex-col gap-4">
    <div class="flex flex-wrap items-center justify-between gap-2">
      <h2 class="text-2xl font-bold tracking-tight">
        Prêts
      </h2>
      <Button as-child>
        <NuxtLink to="/loans/new">Nouveau prêt</NuxtLink>
      </Button>
    </div>

    <p v-if="error" class="text-destructive text-sm">
      {{ error }}
    </p>

    <Card v-else>
      <CardContent class="p-0">
        <div v-if="loading" class="flex items-center justify-center py-12">
          <p class="text-muted-foreground">Chargement…</p>
        </div>
        <template v-else>
          <Table v-if="loans.length > 0">
            <TableHeader>
              <TableRow>
                <TableHead>Client</TableHead>
                <TableHead>Montant</TableHead>
                <TableHead>Taux / Durée</TableHead>
                <TableHead>Statut</TableHead>
                <TableHead>Date déblocage</TableHead>
                <TableHead>Créé le</TableHead>
                <TableHead></TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow v-for="loan in loans" :key="loan.id">
                <TableCell class="font-medium">
                  <NuxtLink :to="`/clients/${loan.client_id}`" class="hover:underline">
                    {{ clientName(loan) }}
                  </NuxtLink>
                </TableCell>
                <TableCell class="tabular-nums">
                  <NumberFlow :value="loan.amount" :format="{ style: 'currency', currency: 'XOF' }" />
                </TableCell>
                <TableCell>
                  {{ loan.interest_rate }}% / {{ loan.duration_months }} mois
                </TableCell>
                <TableCell>
                  <Badge
                    :variant="loan.status === 'en_retard' || loan.status === 'defaut' ? 'destructive' : 'secondary'"
                  >
                    {{ statusLabels[loan.status] }}
                  </Badge>
                </TableCell>
                <TableCell class="text-muted-foreground text-sm">
                  {{ loan.disbursement_date ? new Date(loan.disbursement_date).toLocaleDateString('fr-FR') : '—' }}
                </TableCell>
                <TableCell class="text-muted-foreground text-sm">
                  {{ new Date(loan.created_at).toLocaleDateString('fr-FR') }}
                </TableCell>
                <TableCell>
                  <Button variant="ghost" size="sm" as-child>
                    <NuxtLink :to="`/loans/${loan.id}`">Voir</NuxtLink>
                  </Button>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
          <div v-else class="py-12 text-center text-muted-foreground">
            Aucun prêt.
          </div>
        </template>
      </CardContent>
    </Card>
  </div>
</template>

// src/pages/Loans.tsx
import { useEffect, useState } from 'react';
import { MainLayout } from '@/components/layout/MainLayout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { StatusBadge } from '@/components/ui/status-badge';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Plus, Search } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '@/hooks/useAuth';

interface Loan {
  id: string;
  amount: number;
  duration_months: number;
  status: string;
  created_at: string;
  client: { full_name: string } | null;
}

export default function Loans() {
  const navigate = useNavigate();
  const { role } = useAuth();
  const [loans, setLoans] = useState<Loan[]>([]);
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);
  const canCreateLoans = role === 'directeur' || role === 'agent_credit';

  useEffect(() => {
    const fetchLoans = async () => {
      const { data } = await supabase
        .from('loans')
        .select('id, amount, duration_months, status, created_at, client:clients(full_name)')
        .order('created_at', { ascending: false });
      
      setLoans(data?.map(loan => ({
        ...loan,
        client: Array.isArray(loan.client) ? loan.client[0] : loan.client
      })) || []);
      setLoading(false);
    };
    fetchLoans();
  }, []);

  const formatCurrency = (amount: number) => 
    new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'XOF', maximumFractionDigits: 0 }).format(amount);

  const formatDate = (date: string) => 
    new Date(date).toLocaleDateString('fr-FR', { day: 'numeric', month: 'short', year: 'numeric' });

  const filteredLoans = loans.filter(l =>
    l.client?.full_name?.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <MainLayout>
      <div className="space-y-4 md:space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 sm:gap-4">
          <h1 className="font-display text-2xl md:text-3xl font-bold">Prêts</h1>
          {canCreateLoans && (
            <Link to="/loans/new">
              <Button className="gap-2 w-full sm:w-auto" size="sm">
                <Plus className="w-4 h-4" />
                Nouveau prêt
              </Button>
            </Link>
          )}
        </div>

        <div className="relative max-w-md w-full">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <Input placeholder="Rechercher..." className="pl-10" value={search} onChange={(e) => setSearch(e.target.value)} />
        </div>

        <div className="bg-card rounded-xl border shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <Table>
            <TableHeader>
              <TableRow className="table-header">
                <TableHead>Client</TableHead>
                <TableHead>Montant</TableHead>
                <TableHead>Durée</TableHead>
                <TableHead>Statut</TableHead>
                <TableHead>Date</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {loading ? (
                [...Array(5)].map((_, i) => (
                  <TableRow key={i}>
                    <TableCell colSpan={5}><div className="h-4 bg-muted rounded animate-pulse" /></TableCell>
                  </TableRow>
                ))
              ) : filteredLoans.length > 0 ? (
                filteredLoans.map((loan) => (
                  <TableRow 
                    key={loan.id} 
                    className="cursor-pointer hover:bg-muted/50"
                    onClick={() => navigate(`/loans/${loan.id}`)}
                  >
                    <TableCell className="font-medium">{loan.client?.full_name || 'N/A'}</TableCell>
                    <TableCell>{formatCurrency(loan.amount)}</TableCell>
                    <TableCell>{loan.duration_months} mois</TableCell>
                    <TableCell><StatusBadge status={loan.status as any} /></TableCell>
                    <TableCell className="text-muted-foreground">{formatDate(loan.created_at)}</TableCell>
                  </TableRow>
                ))
              ) : (
                <TableRow>
                  <TableCell colSpan={5} className="text-center py-8 text-muted-foreground">
                    Aucun prêt trouvé
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </div>
      </div>
    </MainLayout>
  );
}
