// src/pages/Users.tsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { MainLayout } from '@/components/layout/MainLayout';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Shield, UserPlus, Loader2, AlertTriangle, Plus, Trash2, Key, MoreHorizontal } from 'lucide-react';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger, DropdownMenuSeparator } from '@/components/ui/dropdown-menu';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { format } from 'date-fns';
import { fr } from 'date-fns/locale';
import { useAuth } from '@/hooks/useAuth';
import type { Database } from '@/integrations/supabase/types';
import { z } from 'zod';

type AppRole = Database['public']['Enums']['app_role'];

interface UserWithRole {
  id: string;
  email: string;
  full_name: string;
  phone: string | null;
  created_at: string;
  role: AppRole | null;
  role_id: string | null;
}

const roleLabels: Record<AppRole, string> = {
  admin: 'Administrateur',
  directeur: 'Directeur',
  agent_credit: 'Agent de crédit',
  caissier: 'Caissier',
  recouvrement: 'Recouvrement',
};

const roleColors: Record<AppRole, string> = {
  admin: 'bg-destructive/10 text-destructive border-destructive/20',
  directeur: 'bg-primary/10 text-primary border-primary/20',
  agent_credit: 'bg-info/10 text-info border-info/20',
  caissier: 'bg-success/10 text-success border-success/20',
  recouvrement: 'bg-warning/10 text-warning border-warning/20',
};

const createUserSchema = z.object({
  email: z.string().email('Email invalide'),
  password: z.string().min(6, 'Le mot de passe doit contenir au moins 6 caractères'),
  full_name: z.string().min(2, 'Le nom complet doit contenir au moins 2 caractères'),
  phone: z.string().optional(),
  role: z.enum(['admin', 'directeur', 'agent_credit', 'caissier', 'recouvrement']),
});

export default function Users() {
  const { role } = useAuth();
  const navigate = useNavigate();
  const [users, setUsers] = useState<UserWithRole[]>([]);
  const [loading, setLoading] = useState(true);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [selectedUser, setSelectedUser] = useState<UserWithRole | null>(null);
  const [selectedRole, setSelectedRole] = useState<AppRole | ''>('');
  const [submitting, setSubmitting] = useState(false);
  const [creating, setCreating] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [changingPassword, setChangingPassword] = useState(false);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [passwordDialogOpen, setPasswordDialogOpen] = useState(false);
  const [userToDelete, setUserToDelete] = useState<UserWithRole | null>(null);
  const [userToChangePassword, setUserToChangePassword] = useState<UserWithRole | null>(null);
  const [newPassword, setNewPassword] = useState('');
  const [newUser, setNewUser] = useState({
    email: '',
    password: '',
    full_name: '',
    phone: '',
    role: '' as AppRole | '',
  });

  // Vérifier si l'utilisateur a accès à la gestion des utilisateurs
  const canManageUsers = role === 'admin' || role === 'directeur';
  const isAdmin = role === 'admin';

  // Les directeurs ne peuvent pas voir ou modifier les admins
  const getVisibleRoles = (): AppRole[] => {
    if (isAdmin) {
      return ['admin', 'directeur', 'agent_credit', 'caissier', 'recouvrement'];
    } else {
      // Les directeurs ne voient pas le rôle admin
      return ['directeur', 'agent_credit', 'caissier', 'recouvrement'];
    }
  };

  const getSelectableRoles = (): AppRole[] => {
    if (isAdmin) {
      return ['admin', 'directeur', 'agent_credit', 'caissier', 'recouvrement'];
    } else {
      // Les directeurs ne peuvent pas assigner le rôle admin
      return ['directeur', 'agent_credit', 'caissier', 'recouvrement'];
    }
  };

  useEffect(() => {
    if (!canManageUsers) {
      navigate('/dashboard');
    }
  }, [canManageUsers, navigate]);

  const fetchUsers = async () => {
    setLoading(true);
    try {
      // Fetch all profiles
      const { data: profiles } = await supabase
        .from('profiles')
        .select('id, email, full_name, phone, created_at')
        .order('created_at', { ascending: false });

      // Fetch all roles
      const { data: roles } = await supabase
        .from('user_roles')
        .select('id, user_id, role');

      // Combine data - filter out admins for directors
      const usersWithRoles: UserWithRole[] = (profiles || [])
        .map(profile => {
          const userRole = roles?.find(r => r.user_id === profile.id);
          return {
            ...profile,
            role: userRole?.role || null,
            role_id: userRole?.id || null,
          };
        })
        .filter(user => {
          // Si c'est un directeur, ne pas montrer les admins
          if (!isAdmin && user.role === 'admin') {
            return false;
          }
          return true;
        });

      setUsers(usersWithRoles);
    } catch (error) {
      console.error('Error fetching users:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchUsers();
  }, []);

  const handleOpenRoleDialog = (user: UserWithRole) => {
    setSelectedUser(user);
    setSelectedRole(user.role || '');
    setDialogOpen(true);
  };

  const handleSaveRole = async () => {
    if (!selectedUser || !selectedRole) return;
    if (!canManageUsers) {
      toast.error('Vous n\'avez pas les permissions nécessaires pour modifier les rôles');
      return;
    }

    // Empêcher un directeur de modifier un admin ou d'assigner le rôle admin
    if (!isAdmin) {
      if (selectedUser.role === 'admin') {
        toast.error('Vous n\'avez pas les permissions nécessaires pour modifier un administrateur');
        return;
      }
      if (selectedRole === 'admin') {
        toast.error('Seul un administrateur peut attribuer le rôle administrateur');
        return;
      }
    }

    setSubmitting(true);
    try {
      if (selectedUser.role_id) {
        // Update existing role
        const { error } = await supabase
          .from('user_roles')
          .update({ role: selectedRole as AppRole })
          .eq('id', selectedUser.role_id);

        if (error) throw error;
      } else {
        // Insert new role
        const { error } = await supabase
          .from('user_roles')
          .insert({ user_id: selectedUser.id, role: selectedRole as AppRole });

        if (error) throw error;
      }

      toast.success('Rôle mis à jour avec succès');
      setDialogOpen(false);
      fetchUsers();
    } catch (error) {
      console.error('Error saving role:', error);
      toast.error('Erreur lors de la mise à jour du rôle');
    } finally {
      setSubmitting(false);
    }
  };

  const handleRemoveRole = async () => {
    if (!selectedUser?.role_id) return;
    if (!canManageUsers) {
      toast.error('Vous n\'avez pas les permissions nécessaires pour supprimer les rôles');
      return;
    }

    setSubmitting(true);
    try {
      const { error } = await supabase
        .from('user_roles')
        .delete()
        .eq('id', selectedUser.role_id);

      if (error) throw error;

      toast.success('Rôle supprimé');
      setDialogOpen(false);
      fetchUsers();
    } catch (error) {
      console.error('Error removing role:', error);
      toast.error('Erreur lors de la suppression du rôle');
    } finally {
      setSubmitting(false);
    }
  };

  const handleCreateUser = async () => {
    if (!canManageUsers) {
      toast.error('Vous n\'avez pas les permissions nécessaires pour créer des utilisateurs');
      return;
    }

    const result = createUserSchema.safeParse(newUser);
    if (!result.success) {
      toast.error(result.error.errors[0].message);
      return;
    }

    setCreating(true);
    try {
      // Create user in auth
      const { data: authData, error: authError } = await supabase.auth.signUp({
        email: newUser.email,
        password: newUser.password,
        options: {
          emailRedirectTo: `${window.location.origin}/`,
          data: {
            full_name: newUser.full_name,
          },
        },
      });

      if (authError) throw authError;
      if (!authData.user) throw new Error('Erreur lors de la création de l\'utilisateur');

      // Wait a bit for the trigger to create the profile
      await new Promise(resolve => setTimeout(resolve, 500));

      // Update profile with phone if provided
      if (newUser.phone) {
        const { error: profileError } = await supabase
          .from('profiles')
          .update({ phone: newUser.phone })
          .eq('id', authData.user.id);

        if (profileError) {
          console.error('Error updating profile:', profileError);
        }
      }

      // Assign role
      const { error: roleError } = await supabase
        .from('user_roles')
        .insert({
          user_id: authData.user.id,
          role: newUser.role as AppRole,
        });

      if (roleError) throw roleError;

      toast.success('Utilisateur créé avec succès');
      setCreateDialogOpen(false);
      setNewUser({
        email: '',
        password: '',
        full_name: '',
        phone: '',
        role: '',
      });
      fetchUsers();
    } catch (error: any) {
      console.error('Error creating user:', error);
      if (error.message.includes('already registered') || error.message.includes('already exists')) {
        toast.error('Cet email est déjà utilisé');
      } else {
        toast.error('Erreur lors de la création de l\'utilisateur');
      }
    } finally {
      setCreating(false);
    }
  };

  const handleDeleteUser = async () => {
    if (!userToDelete || !isAdmin) return;

    setDeleting(true);
    try {
      const response = await fetch(
        `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/manage-users`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${(await supabase.auth.getSession()).data.session?.access_token}`,
          },
          body: JSON.stringify({
            action: 'delete',
            userId: userToDelete.id,
          }),
        }
      );

      const result = await response.json();
      
      if (!response.ok) {
        throw new Error(result.error || 'Erreur lors de la suppression');
      }

      toast.success('Utilisateur supprimé avec succès');
      setDeleteDialogOpen(false);
      setUserToDelete(null);
      fetchUsers();
    } catch (error: any) {
      console.error('Error deleting user:', error);
      toast.error(error.message || 'Erreur lors de la suppression de l\'utilisateur');
    } finally {
      setDeleting(false);
    }
  };

  const handleChangePassword = async () => {
    if (!userToChangePassword || !isAdmin || !newPassword) return;

    if (newPassword.length < 6) {
      toast.error('Le mot de passe doit contenir au moins 6 caractères');
      return;
    }

    setChangingPassword(true);
    try {
      const response = await fetch(
        `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/manage-users`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${(await supabase.auth.getSession()).data.session?.access_token}`,
          },
          body: JSON.stringify({
            action: 'update_password',
            userId: userToChangePassword.id,
            newPassword: newPassword,
          }),
        }
      );

      const result = await response.json();
      
      if (!response.ok) {
        throw new Error(result.error || 'Erreur lors de la modification');
      }

      toast.success('Mot de passe modifié avec succès');
      setPasswordDialogOpen(false);
      setUserToChangePassword(null);
      setNewPassword('');
    } catch (error: any) {
      console.error('Error changing password:', error);
      toast.error(error.message || 'Erreur lors de la modification du mot de passe');
    } finally {
      setChangingPassword(false);
    }
  };

  const formatDate = (date: string) =>
    format(new Date(date), 'dd MMM yyyy', { locale: fr });

  if (!canManageUsers) {
    return (
      <MainLayout>
        <Alert variant="destructive">
          <AlertTriangle className="h-4 w-4" />
          <AlertTitle>Accès refusé</AlertTitle>
          <AlertDescription>
            Vous n'avez pas les permissions nécessaires pour accéder à la gestion des utilisateurs.
            Seuls les Administrateurs et Directeurs peuvent gérer les utilisateurs.
          </AlertDescription>
        </Alert>
      </MainLayout>
    );
  }

  return (
    <MainLayout>
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <h1 className="font-display text-3xl font-bold">Gestion des Utilisateurs</h1>
          {canManageUsers && (
            <Button onClick={() => setCreateDialogOpen(true)} className="gap-2">
              <Plus className="w-4 h-4" />
              Créer un utilisateur
            </Button>
          )}
        </div>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Shield className="w-5 h-5" />
              Liste des utilisateurs
            </CardTitle>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow className="table-header">
                  <TableHead>Utilisateur</TableHead>
                  <TableHead>Email</TableHead>
                  <TableHead>Téléphone</TableHead>
                  <TableHead>Rôle</TableHead>
                  <TableHead>Inscription</TableHead>
                  <TableHead></TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {loading ? (
                  [...Array(5)].map((_, i) => (
                    <TableRow key={i}>
                      <TableCell colSpan={6}>
                        <div className="h-4 bg-muted rounded animate-pulse" />
                      </TableCell>
                    </TableRow>
                  ))
                ) : users.length > 0 ? (
                  users.map((user) => (
                    <TableRow key={user.id}>
                      <TableCell>
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center">
                            <span className="font-medium text-primary">
                              {user.full_name?.charAt(0)?.toUpperCase() || 'U'}
                            </span>
                          </div>
                          <span className="font-medium">{user.full_name}</span>
                        </div>
                      </TableCell>
                      <TableCell className="text-muted-foreground">{user.email}</TableCell>
                      <TableCell className="text-muted-foreground">{user.phone || '-'}</TableCell>
                      <TableCell>
                        {user.role ? (
                          <Badge className={roleColors[user.role]}>
                            {roleLabels[user.role]}
                          </Badge>
                        ) : (
                          <Badge variant="outline" className="text-muted-foreground">
                            Aucun rôle
                          </Badge>
                        )}
                      </TableCell>
                      <TableCell className="text-muted-foreground">
                        {formatDate(user.created_at)}
                      </TableCell>
                      <TableCell>
                        {canManageUsers && (
                          <div className="flex items-center gap-2">
                            <Button
                              size="sm"
                              variant="outline"
                              onClick={() => handleOpenRoleDialog(user)}
                            >
                              <UserPlus className="w-4 h-4 mr-1" />
                              Rôle
                            </Button>
                            {isAdmin && (
                              <DropdownMenu>
                                <DropdownMenuTrigger asChild>
                                  <Button size="sm" variant="ghost">
                                    <MoreHorizontal className="w-4 h-4" />
                                  </Button>
                                </DropdownMenuTrigger>
                                <DropdownMenuContent align="end">
                                  <DropdownMenuItem
                                    onClick={() => {
                                      setUserToChangePassword(user);
                                      setNewPassword('');
                                      setPasswordDialogOpen(true);
                                    }}
                                  >
                                    <Key className="w-4 h-4 mr-2" />
                                    Modifier mot de passe
                                  </DropdownMenuItem>
                                  <DropdownMenuSeparator />
                                  <DropdownMenuItem
                                    className="text-destructive"
                                    onClick={() => {
                                      setUserToDelete(user);
                                      setDeleteDialogOpen(true);
                                    }}
                                  >
                                    <Trash2 className="w-4 h-4 mr-2" />
                                    Supprimer
                                  </DropdownMenuItem>
                                </DropdownMenuContent>
                              </DropdownMenu>
                            )}
                          </div>
                        )}
                      </TableCell>
                    </TableRow>
                  ))
                ) : (
                  <TableRow>
                    <TableCell colSpan={6} className="text-center py-8 text-muted-foreground">
                      Aucun utilisateur trouvé
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </CardContent>
        </Card>

        {/* Create User Dialog */}
        <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
          <DialogContent className="max-w-md">
            <DialogHeader>
              <DialogTitle>Créer un nouvel utilisateur</DialogTitle>
            </DialogHeader>
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="email">Email *</Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="exemple@email.com"
                  value={newUser.email}
                  onChange={(e) => setNewUser({ ...newUser, email: e.target.value })}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="password">Mot de passe *</Label>
                <Input
                  id="password"
                  type="password"
                  placeholder="Minimum 6 caractères"
                  value={newUser.password}
                  onChange={(e) => setNewUser({ ...newUser, password: e.target.value })}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="full_name">Nom complet *</Label>
                <Input
                  id="full_name"
                  type="text"
                  placeholder="Jean Dupont"
                  value={newUser.full_name}
                  onChange={(e) => setNewUser({ ...newUser, full_name: e.target.value })}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="phone">Téléphone</Label>
                <Input
                  id="phone"
                  type="tel"
                  placeholder="+33 6 12 34 56 78"
                  value={newUser.phone}
                  onChange={(e) => setNewUser({ ...newUser, phone: e.target.value })}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="role">Rôle *</Label>
                <Select
                  value={newUser.role}
                  onValueChange={(v) => setNewUser({ ...newUser, role: v as AppRole })}
                >
                  <SelectTrigger id="role">
                    <SelectValue placeholder="Sélectionner un rôle" />
                  </SelectTrigger>
                  <SelectContent>
                    {getSelectableRoles().map((r) => (
                      <SelectItem key={r} value={r}>{roleLabels[r]}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="flex justify-end gap-3 pt-4">
                <Button
                  variant="outline"
                  onClick={() => {
                    setCreateDialogOpen(false);
                    setNewUser({
                      email: '',
                      password: '',
                      full_name: '',
                      phone: '',
                      role: '',
                    });
                  }}
                  disabled={creating}
                >
                  Annuler
                </Button>
                <Button
                  onClick={handleCreateUser}
                  disabled={creating || !newUser.email || !newUser.password || !newUser.full_name || !newUser.role}
                >
                  {creating && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                  Créer
                </Button>
              </div>
            </div>
          </DialogContent>
        </Dialog>

        {/* Role Dialog */}
        <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Modifier le rôle</DialogTitle>
            </DialogHeader>
            {selectedUser && (
              <div className="space-y-4">
                <div className="p-4 rounded-lg bg-muted/50">
                  <p className="font-medium">{selectedUser.full_name}</p>
                  <p className="text-sm text-muted-foreground">{selectedUser.email}</p>
                </div>

                <div className="space-y-2">
                  <label className="text-sm font-medium">Rôle</label>
                  <Select value={selectedRole} onValueChange={(v) => setSelectedRole(v as AppRole)}>
                    <SelectTrigger>
                      <SelectValue placeholder="Sélectionner un rôle" />
                    </SelectTrigger>
                    <SelectContent>
                      {getSelectableRoles().map((r) => (
                        <SelectItem key={r} value={r}>{roleLabels[r]}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="flex justify-between pt-4">
                  {selectedUser.role && (
                    <Button
                      variant="destructive"
                      onClick={handleRemoveRole}
                      disabled={submitting}
                    >
                      Supprimer le rôle
                    </Button>
                  )}
                  <div className="flex gap-3 ml-auto">
                    <Button variant="outline" onClick={() => setDialogOpen(false)}>
                      Annuler
                    </Button>
                    <Button onClick={handleSaveRole} disabled={submitting || !selectedRole}>
                      {submitting && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                      Enregistrer
                    </Button>
                  </div>
                </div>
              </div>
            )}
          </DialogContent>
        </Dialog>

        {/* Delete Confirmation Dialog */}
        <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Supprimer l'utilisateur</AlertDialogTitle>
              <AlertDialogDescription>
                Êtes-vous sûr de vouloir supprimer l'utilisateur{' '}
                <strong>{userToDelete?.full_name}</strong> ({userToDelete?.email}) ?
                Cette action est irréversible.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel disabled={deleting}>Annuler</AlertDialogCancel>
              <AlertDialogAction
                onClick={handleDeleteUser}
                disabled={deleting}
                className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              >
                {deleting && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                Supprimer
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>

        {/* Password Change Dialog */}
        <Dialog open={passwordDialogOpen} onOpenChange={setPasswordDialogOpen}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Modifier le mot de passe</DialogTitle>
            </DialogHeader>
            {userToChangePassword && (
              <div className="space-y-4">
                <div className="p-4 rounded-lg bg-muted/50">
                  <p className="font-medium">{userToChangePassword.full_name}</p>
                  <p className="text-sm text-muted-foreground">{userToChangePassword.email}</p>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="new-password">Nouveau mot de passe</Label>
                  <Input
                    id="new-password"
                    type="password"
                    placeholder="Minimum 6 caractères"
                    value={newPassword}
                    onChange={(e) => setNewPassword(e.target.value)}
                  />
                </div>

                <div className="flex justify-end gap-3 pt-4">
                  <Button
                    variant="outline"
                    onClick={() => {
                      setPasswordDialogOpen(false);
                      setNewPassword('');
                    }}
                    disabled={changingPassword}
                  >
                    Annuler
                  </Button>
                  <Button
                    onClick={handleChangePassword}
                    disabled={changingPassword || !newPassword || newPassword.length < 6}
                  >
                    {changingPassword && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                    Modifier
                  </Button>
                </div>
              </div>
            )}
          </DialogContent>
        </Dialog>
      </div>
    </MainLayout>
  );
}

// app/pages/users/index.vue
<script setup lang="ts">
import type { AppRole } from '~/types/database'
import { roleLabels as accessRoleLabels } from '~/constants/menuAccess'

definePageMeta({ layout: 'default' })

interface UserWithRole {
  id: string
  email: string
  full_name: string
  phone: string | null
  created_at: string
  role: AppRole | string | null
}

const users = ref<UserWithRole[]>([])
const loading = ref(true)
const error = ref('')
const createDialogOpen = ref(false)
const creating = ref(false)
const createError = ref('')
const editDialogOpen = ref(false)
const editing = ref(false)
const editError = ref('')
const editUser = ref<UserWithRole | null>(null)
const editForm = ref({ full_name: '', phone: '', role: '' as AppRole | '', new_password: '' })

const { role: currentUserRole } = useAuthRole()
const config = useRuntimeConfig().public
const supabase = useSupabase()

const roleLabels: Record<string, string> = {
  ...accessRoleLabels,
  agent: 'Agent',
}

const form = ref({
  email: '',
  password: '',
  full_name: '',
  phone: '',
  role: '' as AppRole | '',
})

const roleOptions = computed<AppRole[]>(() => {
  const all: AppRole[] = ['admin', 'directeur', 'agent_credit', 'caissier', 'recouvrement']
  if (currentUserRole.value === 'admin') return all
  if (currentUserRole.value === 'directeur') return ['directeur', 'agent_credit', 'caissier', 'recouvrement']
  return []
})

function canEditUser(u: UserWithRole) {
  if (roleOptions.value.length === 0) return false
  if (currentUserRole.value === 'admin') return true
  if (currentUserRole.value === 'directeur') return u.role !== 'admin'
  return false
}

const editRoleOptions = computed<AppRole[]>(() => {
  const opts = roleOptions.value
  const u = editUser.value
  if (!u?.role || opts.includes(u.role as AppRole)) return opts
  return [...opts, u.role as AppRole]
})

async function fetchUsers() {
  loading.value = true
  error.value = ''
  try {
    if (!supabase) {
      error.value = 'Supabase non configuré.'
      return
    }
    const { data: profilesData, error: e1 } = await supabase.from('profiles').select('id, email, full_name, phone, created_at').order('created_at', { ascending: false })
    if (e1) throw e1
    const { data: rolesData } = await supabase.from('user_roles').select('user_id, role')
    const roleByUser = (rolesData ?? []).reduce((acc: Record<string, string>, r: any) => {
      acc[r.user_id] = r.role
      return acc
    }, {})
    users.value = (profilesData ?? []).map(p => ({
      ...p,
      role: roleByUser[p.id] ?? null,
    }))
  }
  catch (e: any) {
    error.value = e?.message || 'Erreur chargement utilisateurs'
  }
  finally {
    loading.value = false
  }
}

async function createUser() {
  createError.value = ''
  if (!form.value.email.trim() || !form.value.password || !form.value.full_name.trim() || !form.value.role) {
    createError.value = 'Email, mot de passe, nom et rôle sont requis.'
    return
  }
  if (form.value.password.length < 6) {
    createError.value = 'Le mot de passe doit contenir au moins 6 caractères.'
    return
  }
  creating.value = true
  try {
    const { data: { session } } = await supabase!.auth.getSession()
    const token = session?.access_token
    if (!token) {
      createError.value = 'Session expirée. Reconnectez-vous.'
      return
    }
    const baseUrl = (config.supabaseUrl as string) || ''
    if (!baseUrl) {
      createError.value = 'Configuration Supabase manquante (NUXT_PUBLIC_SUPABASE_URL).'
      return
    }
    const url = `${baseUrl}/functions/v1/manage-users`
    const res = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`,
      },
      body: JSON.stringify({
        action: 'create_user',
        email: form.value.email.trim(),
        password: form.value.password,
        fullName: form.value.full_name.trim(),
        phone: form.value.phone?.trim() || null,
        role: form.value.role,
      }),
    })
    const text = await res.text()
    let data: { error?: string; message?: string } = {}
    try {
      data = text ? JSON.parse(text) : {}
    }
    catch {
      data = { error: text || 'Réponse invalide' }
    }
    if (!res.ok) {
      createError.value = data.error || data.message || `Erreur ${res.status}`
      return
    }
    createDialogOpen.value = false
    form.value = { email: '', password: '', full_name: '', phone: '', role: '' }
    await fetchUsers()
  }
  catch (e: any) {
    createError.value = e?.message || 'Erreur lors de la création'
  }
  finally {
    creating.value = false
  }
}

function openCreateDialog() {
  createError.value = ''
  form.value = { email: '', password: '', full_name: '', phone: '', role: roleOptions.value[0] || '' }
  createDialogOpen.value = true
}

function openEditDialog(u: UserWithRole) {
  editUser.value = u
  editForm.value = {
    full_name: u.full_name,
    phone: u.phone ?? '',
    role: (u.role as AppRole) ?? '',
    new_password: '',
  }
  editError.value = ''
  editDialogOpen.value = true
}

async function callManageUsers(body: Record<string, unknown>): Promise<{ ok: boolean; error?: string }> {
  const { data: { session } } = await supabase!.auth.getSession()
  const token = session?.access_token
  if (!token) return { ok: false, error: 'Session expirée. Reconnectez-vous.' }
  const baseUrl = (config.supabaseUrl as string) || ''
  if (!baseUrl) return { ok: false, error: 'Configuration Supabase manquante.' }
  const res = await fetch(`${baseUrl}/functions/v1/manage-users`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
    body: JSON.stringify(body),
  })
  const text = await res.text()
  let data: { error?: string; message?: string } = {}
  try { data = text ? JSON.parse(text) : {} } catch { data = { error: text || 'Réponse invalide' } }
  if (!res.ok) return { ok: false, error: data.error || data.message || `Erreur ${res.status}` }
  return { ok: true }
}

async function saveEdit() {
  const u = editUser.value
  if (!u) return
  editError.value = ''
  const { full_name, phone, role: newRole, new_password } = editForm.value
  if (!full_name.trim()) {
    editError.value = 'Le nom est requis.'
    return
  }
  if (!newRole) {
    editError.value = 'Le rôle est requis.'
    return
  }
  if (new_password && new_password.length < 6) {
    editError.value = 'Le mot de passe doit contenir au moins 6 caractères.'
    return
  }
  editing.value = true
  try {
    if (full_name.trim() !== u.full_name || phone !== (u.phone ?? '')) {
      const r = await callManageUsers({
        action: 'update_profile',
        userId: u.id,
        fullName: full_name.trim(),
        phone: phone?.trim() || null,
      })
      if (!r.ok) {
        editError.value = r.error
        return
      }
    }
    if (newRole !== (u.role ?? '')) {
      const r = await callManageUsers({ action: 'update_role', userId: u.id, role: newRole })
      if (!r.ok) {
        editError.value = r.error
        return
      }
    }
    if (new_password) {
      const r = await callManageUsers({ action: 'update_password', userId: u.id, newPassword: new_password })
      if (!r.ok) {
        editError.value = r.error
        return
      }
    }
    editDialogOpen.value = false
    editUser.value = null
    await fetchUsers()
  }
  finally {
    editing.value = false
  }
}

onMounted(() => fetchUsers())
</script>

<template>
  <div class="w-full flex flex-col gap-4">
    <div class="flex flex-wrap items-center justify-between gap-2">
      <h2 class="text-2xl font-bold tracking-tight">
        Utilisateurs
      </h2>
      <Button v-if="roleOptions.length > 0" @click="openCreateDialog">
        Créer un employé
      </Button>
    </div>
    <p v-if="error" class="text-destructive text-sm">
      {{ error }}
    </p>
    <Card v-else>
      <CardContent class="p-0">
        <div v-if="loading" class="flex items-center justify-center py-12">
          <p class="text-muted-foreground">Chargement…</p>
        </div>
        <template v-else>
          <Table v-if="users.length > 0">
<TableHeader>
            <TableRow>
                <TableHead>Nom</TableHead>
                <TableHead>Email</TableHead>
                <TableHead>Téléphone</TableHead>
                <TableHead>Rôle</TableHead>
                <TableHead>Créé le</TableHead>
                <TableHead v-if="roleOptions.length > 0" class="w-[100px] text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow v-for="u in users" :key="u.id">
                <TableCell class="font-medium">{{ u.full_name }}</TableCell>
                <TableCell>{{ u.email }}</TableCell>
                <TableCell>{{ u.phone || '—' }}</TableCell>
                <TableCell>
                  <Badge variant="secondary">
                    {{ roleLabels[u.role as string] ?? u.role ?? '—' }}
                  </Badge>
                </TableCell>
                <TableCell class="text-muted-foreground text-sm">
                  {{ new Date(u.created_at).toLocaleDateString('fr-FR') }}
                </TableCell>
                <TableCell v-if="canEditUser(u)" class="text-right">
                  <Button variant="ghost" size="sm" @click="openEditDialog(u)">
                    Modifier
                  </Button>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
          <div v-else class="py-12 text-center text-muted-foreground">
            Aucun utilisateur.
          </div>
        </template>
      </CardContent>
    </Card>

    <Dialog v-model:open="createDialogOpen">
      <DialogContent class="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Créer un compte employé</DialogTitle>
          <DialogDescription>
            L’employé pourra se connecter avec cet email et ce mot de passe. Le rôle définit ses accès.
          </DialogDescription>
        </DialogHeader>
        <form class="flex flex-col gap-4" @submit.prevent="createUser">
          <p v-if="createError" class="text-destructive text-sm">
            {{ createError }}
          </p>
          <div class="grid gap-2">
            <Label for="new_email">Email *</Label>
            <Input id="new_email" v-model="form.email" type="email" placeholder="employe@exemple.com" required />
          </div>
          <div class="grid gap-2">
            <Label for="new_password">Mot de passe * (min. 6 caractères)</Label>
            <Input id="new_password" v-model="form.password" type="password" placeholder="••••••••" required />
          </div>
          <div class="grid gap-2">
            <Label for="new_full_name">Nom complet *</Label>
            <Input id="new_full_name" v-model="form.full_name" placeholder="Prénom Nom" required />
          </div>
          <div class="grid gap-2">
            <Label for="new_phone">Téléphone</Label>
            <Input id="new_phone" v-model="form.phone" type="tel" placeholder="+221 77 123 45 67" />
          </div>
          <div class="grid gap-2">
            <Label for="new_role">Rôle *</Label>
            <Select v-model="form.role" required>
              <SelectTrigger id="new_role">
                <SelectValue placeholder="Choisir un rôle" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem v-for="r in roleOptions" :key="r" :value="r">
                  {{ roleLabels[r] }}
                </SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div class="flex justify-end gap-2">
            <Button type="button" variant="outline" @click="createDialogOpen = false">
              Annuler
            </Button>
            <Button type="submit" :disabled="creating">
              {{ creating ? 'Création…' : 'Créer le compte' }}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>

    <Dialog v-model:open="editDialogOpen">
      <DialogContent class="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Modifier l'employé</DialogTitle>
          <DialogDescription>
            Modifier le nom, le numéro, le rôle ou le mot de passe. Laissez le mot de passe vide pour ne pas le changer.
          </DialogDescription>
        </DialogHeader>
        <form v-if="editUser" class="flex flex-col gap-4" @submit.prevent="saveEdit">
          <p v-if="editError" class="text-destructive text-sm">
            {{ editError }}
          </p>
          <div class="grid gap-2">
            <Label for="edit_full_name">Nom complet *</Label>
            <Input id="edit_full_name" v-model="editForm.full_name" placeholder="Prénom Nom" required />
          </div>
          <div class="grid gap-2">
            <Label for="edit_phone">Téléphone</Label>
            <Input id="edit_phone" v-model="editForm.phone" type="tel" placeholder="+221 77 123 45 67" />
          </div>
          <div class="grid gap-2">
            <Label for="edit_role">Rôle *</Label>
            <Select v-model="editForm.role" required>
              <SelectTrigger id="edit_role">
                <SelectValue placeholder="Choisir un rôle" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem v-for="r in editRoleOptions" :key="r" :value="r">
                  {{ roleLabels[r] }}
                </SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div class="grid gap-2">
            <Label for="edit_password">Nouveau mot de passe (optionnel)</Label>
            <Input id="edit_password" v-model="editForm.new_password" type="password" placeholder="Laisser vide pour ne pas changer" />
          </div>
          <div class="flex justify-end gap-2">
            <Button type="button" variant="outline" @click="editDialogOpen = false">
              Annuler
            </Button>
            <Button type="submit" :disabled="editing">
              {{ editing ? 'Enregistrement…' : 'Enregistrer' }}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  </div>
</template>
